######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 11 00:50:37 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cc
