######################################################################
# Automatically generated by qmake (2.01a) Thu Mar 12 03:27:59 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += dialog.h
SOURCES += dialog.cc main.cc
